apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: tjd2p2ovi-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:2a5e84c5a4be0d8154f62789451820e0b9454f83@sha256:b63eb9ff4e209298d12c9fb92d228d18499881c6a2e6ee36d6d59c3d62edff66
          name: container-image
